// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/Diwamoto/tgk"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeTGKManager はTGKマネージャーとその依存関係を初期化します
func InitializeTGKManager() tgk.TGKManager {
	hidService := tgk.NewHIDService()
	keyScanService := tgk.NewKeyScanService()
	configRepository := tgk.NewConfigRepository()
	keymapRepository := tgk.NewKeymapRepository(configRepository)
	layerService := tgk.NewLayerService(keymapRepository, configRepository)
	remapService := tgk.NewRemapService()
	splitService := tgk.NewSplitService()
	configService := tgk.NewConfigService(configRepository)
	tgkManager := tgk.NewTGKManager(hidService, keyScanService, layerService, remapService, splitService, configService)
	return tgkManager
}

// wire.go:

// repositorySet はリポジトリの依存関係を提供します
var repositorySet = wire.NewSet(tgk.NewGPIORepository, tgk.NewKeymapRepository, tgk.NewConfigRepository)

// serviceSet はサービスの依存関係を提供します
var serviceSet = wire.NewSet(tgk.NewHIDService, tgk.NewKeyScanService, tgk.NewLayerService, tgk.NewRemapService, tgk.NewSplitService, tgk.NewConfigService)
